### ISSUE TITLE
How to access the CDM v5 version of the omoponfhir-r4-server?

### ISSUE THREAD

**Issue by mmtrun** [omoponfhir/omoponfhir-r4-server#2]
It seems that the current version of the R4 server is configured for CDM v6. I do not see branches or tags for the CDM v5 version. I have attempted to workaround this by cloning the CDM v6 server and changing references to omopv6 in RestfulServlet.java, FhirServerConfig.Java and SMARTonFHIRConformanceStatement.java.

**Comment by fabiomela** [comment]
Hi @mmtrun, were you successful with your attempt? Is it possible to use the R4 server with the CDM v5 mapping?

**Comment by mmtrun** [comment]
Yes, I did get it to work with a little fiddling. Let me know if you want
details.

**Comment by fabiomela** [comment]
Great, if you don't mind yes, I need the details.

I've tried to follow your indication, editing: RestfulServlet.java, FhirServerConfig.Java and SMARTonFHIRConformanceStatement.java, but I still have some issues trying to start the server.

Thank you in advance.

**Comment by myungchoi** [comment]
Sorry for late response. The following repo will be our main repo for OMOPv5 over R4. 
https://github.com/omoponfhir/omoponfhir-main-r4-sql

Several folks reported that this installs correctly.
